### ISSUE TITLE
Incorrect highlighting for  DO / END

### ISSUE THREAD

**Issue by proulxwz** [appliedengdesign/vscode-gcode-syntax#1]
This code shows incorrect highlighting for DO/ENDDO
(********************************)
WHILE[1.EQ1.]DO1(MAIN*LOOP)
(********************************)
#3004=0
#28=0(LOOP*CHECKING)
WHILE[ABS[#[#5+7.]]LT0.1]DO2(WAIT*FOR*OPCODE)
G04X#[#31+10.]
#28=#28+1
IF[#28 LT 5000] GOTO300
#33=78
GOTO9000
N300
END2

![image](https://user-images.githubusercontent.com/47320932/52207158-cfde0300-287c-11e9-82fd-6a6d31574259.png)

You will see that the While statement's "DO2" highlights the "O2"  and the END2 Statement has the "D2" portion highlighted.

**Comment by mikecentola** [comment]
Fixed this. Will release v0.1.1 here shortly.

**Comment by mikecentola** [comment]
@proulxwz Just published v0.1.1 to the marketplace. Let me know if that fixes the issues. Thanks!

**Comment by mikecentola** [comment]
Closing issue by EOB today unless its still not working

**Comment by proulxwz** [comment]
Looks good now!  Thanks

**Comment by mikecentola** [comment]
Great!
