### ISSUE TITLE
Add a new type of machine 

### ISSUE THREAD

**Issue by Bastien42** [appliedengdesign/vscode-gcode-syntax#12]
Is it possible to add a new type of machine with the new m and g code associated with it 

coordinate grinding i'll link the g and m code related to the machine it will be in french i can make the translation for you in english if you want 
[M code.pdf](https://github.com/appliedengdesign/vscode-gcode-syntax/files/5384539/M.code.pdf)
[G code.pdf](https://github.com/appliedengdesign/vscode-gcode-syntax/files/5384540/G.code.pdf)

**Comment by mikecentola** [comment]
I'm actually working on the ability to have the machine change actually do something. I want it to change snippets and coloring based on the machine type. It might be a little bit to get that all set but I'll keep you updated. Thanks for the suggestion!
