### ISSUE TITLE
.ngc file support for LinuxCnc

### ISSUE THREAD

**Issue by 85vmh** [appliedengdesign/vscode-gcode-syntax#14]
Natively, the LinuxCnc files have .ngc extension
Can you please add suport for this extension too?
I've renamed a file to have .nc extension and it works fine, just that the .ngc files are not recognized by default.
Thanks for the great work!

**Comment by mikecentola** [comment]
Yup not a problem! Will add it to the next update :)

**Comment by mikecentola** [comment]
Fixed in 0.4.1 just uploaded!
