### ISSUE TITLE
File Extensions for Okuma OSP controls

### ISSUE THREAD

**Issue by Blackblade1941** [appliedengdesign/vscode-gcode-syntax#15]
You have .min (main program) extension for OSP control but there are a few other commonly used extensions when programming for the OSP as well:

.ssb (System Sub Program)
.sub (User Sub Program)
.lib (Library Program)

Would it be possible to add these in as well?

**Comment by mikecentola** [comment]
I'll get this added to the next update! Thanks!

**Comment by mikecentola** [comment]
Fixed in 0.4.1 just uploaded!
