### ISSUE TITLE
Сolorization of the G-code with a dot

### ISSUE THREAD

**Issue by anzory** [appliedengdesign/vscode-gcode-syntax#16]
If the G-code is with a dot, the colorization of the G-code does not work.
For example G68.2 
 (used in FANUC Series 30i/300i/300is-MODEL A, FANUC Series 31i/310i/310is-MODEL A, FANUC Series 32i/320i/320is-MODEL A)
![image](https://user-images.githubusercontent.com/1932867/105621921-6fac4700-5e2e-11eb-9c5b-e005ceca581d.png)

**Comment by mikecentola** [comment]
Will add it to the next update Thanks!

**Comment by mikecentola** [comment]
Fixed in 0.4.1 just uploaded!
