### ISSUE TITLE
Line Numbering

### ISSUE THREAD

**Issue by shadowbane900** [appliedengdesign/vscode-gcode-syntax#17]
add Line numbering/ renumbering function

**Comment by mikecentola** [comment]
Can you describe a little more what you're looking for?

**Comment by shadowbane900** [comment]
in software such as cimco edit and predator editor can add line numbers i.e. N100 N110 and re number them as needed

**Comment by mikecentola** [comment]
ok shouldn't be too hard to get that working. I'll add it to 0.6 roadmap.

**Comment by silopolis** [comment]
This one too would be nice to have ! :+1: 
Being able to act on whole program as well as selected blocks would be great.
Option to ignore blank lines and comment blocks (other specific blocks ?) would be nice.

**Comment by mikecentola** [comment]
@silopolis Right now it acts on the whole file, but has the options to ignore blanks and comments in the settings. Shouldn't be too hard to add the ability to act on selected blocks.

**Comment by silopolis** [comment]
Nice, thanks 👍🙏

**Comment by mikecentola** [comment]
Line numbering added to v0.7

**Comment by silopolis** [comment]
Le mar. 30 nov. 2021 à 23:44, Mike Centola ***@***.***> a
écrit :

> Line numbering added to v0.7
>
Nice thanks 👍
