### ISSUE TITLE
Math expressions incorrectly highlighted

### ISSUE THREAD

**Issue by proulxwz** [appliedengdesign/vscode-gcode-syntax#2]
Please see this screenshot:
![image](https://user-images.githubusercontent.com/47320932/52207239-17648f00-287d-11e9-9d5a-2217b361af1a.png)

Note that this line:
WHILE[ABS[#[#5+7.]]LT0.1]DO2(WAIT*FOR*OPCODE)

has the ABS function incorrectly highlighting the "S"

**Comment by mikecentola** [comment]
@proulxwz Just published v0.1.1 to the marketplace. Let me know if that fixes the issues. Thanks!

**Comment by mikecentola** [comment]
@proulxwz let me know if this didn't work. will close issue by EOB today.

**Comment by proulxwz** [comment]
Works fine now.   Looks good.

**Comment by mikecentola** [comment]
Great!
