### ISSUE TITLE
Typo in CONTRIBUTING

### ISSUE THREAD

**Issue by BelKed** [appliedengdesign/vscode-gcode-syntax#20]
**Describe the bug**
In [CONTRIBUTING.md](https://github.com/appliedengdesign/vscode-gcode-syntax/blob/master/CONTRIBUTING.md) is typo in line
> Submit a pull request tot he development branch of the vscode-gcode-syntax respository.

**To Reproduce**
1. Go to https://github.com/appliedengdesign/vscode-gcode-syntax/blob/master/CONTRIBUTING.md.
2. Scroll down to line
> Submit a pull request tot he development branch of the vscode-gcode-syntax respository.
3. See error

**Expected behavior**
This line should be:

Submit a pull request to the development branch of the vscode-gcode-syntax respository.

or maybe better:

Submit a pull request to the development branch of the [vscode-gcode-syntax](https://github.com/appliedengdesign/vscode-gcode-syntax) respository.

**Comment by mikecentola** [comment]
Thank you!

**Comment by mikecentola** [comment]
Just released v0.5.0. Fixed.
