### ISSUE TITLE
Add hover text description of G-Codes

### ISSUE THREAD

**Issue by BelKed** [appliedengdesign/vscode-gcode-syntax#21]
**Suggest a Feature you'd like to see**
I suggest to add hover text description of G-Codes. Related to: https://github.com/Milys/NC-Gcode-VSCode/pull/9.

**Additional context**
When you hover G-Code, this should show short description and link to more info (source website).
Source website is: https://marlinfw.org/meta/gcode.

**Comment by mikecentola** [comment]
Great idea. I'll see if I can swing it into 0.6

**Comment by shapesorter** [comment]
If it would be possible to make this a configurable option, as many will not use Marlins G-code.  Fancy would be allowing links to documentation that is machine specific, or a file where we could build our own list.

**Comment by BelKed** [comment]
Good suggestion. But that link should be link to API...

**Comment by shapesorter** [comment]
I don't know how to do an API, but I understand the general idea, if there is help that I can give, as a CNC guy I would like to do it.  I do not know what that is, so when you see it say something to me.

**Comment by mikecentola** [comment]
@shapesorter @BelKed  I decided to make my own NPM module for this. It is going to take JSON files that I wrote a schema for similar to Marlin. It'll have CNC Milling, CNC turning and 3D printing descriptions. I did it as a separate project so that people can contribute to the descriptions as well.

[gcode-reference](https://github.com/appliedengdesign/gcode-reference)

Also I'll put some logic into there to automagically convert to HTML, markdown, etc. Might make for a great overall community reference that isn't machine-specific.

**Comment by mikecentola** [comment]
Could even build it out as a consumable API

**Comment by BelKed** [comment]
Nice 😄

**Comment by shapesorter** [comment]
Very

**Comment by shapesorter** [comment]
Now all I have to to is figure out how to use it.  Any way you could screenshot where to add the g-code info?  I will be able to figure from there.

**Comment by mikecentola** [comment]
@shapesorter I would LOVE for you guys to help out with the descrptions. Let me finish the schema and the basic code for the module and then I'll make an easy way for people to contribute to it.

**Comment by BelKed** [comment]
I could help you, just write, when it's finished 😄

**Comment by shapesorter** [comment]
Well, I would LOVE to help make it better.  Mostly I just use it as a coloring scheme, but the potential is great.

**Comment by mikecentola** [comment]
@shapesorter @BelKed Made some progress drafting up a skeleton of the package. Have a look and let me know what you think. I wanted to at least get the JSON schema written and some skeleton files up there. Mainly check out the format of the JSON files, and let me know if that's enough information to store about each code. Thanks!

[gcode-reference](https://github.com/appliedengdesign/gcode-reference)

**Comment by BelKed** [comment]
I think, there should be also optional field `link` pointing to the source...

**Comment by mikecentola** [comment]
@BelKed Like pointing back to a web reference of the same thing? Or to a different website that has it listed?

**Comment by BelKed** [comment]
To a different website that has it listed – with examples or something like that...
For example: `M00` will point to https://marlinfw.org/docs/gcode/G000-G001.html

**Comment by mikecentola** [comment]
Oh boy!!

![image](https://user-images.githubusercontent.com/12663057/114901455-d2383200-9de2-11eb-8022-b2ef7f37d649.png)

**Comment by mikecentola** [comment]
Added to v0.6.0. Still need to work on more descriptions in [gcode-reference](https://github.com/appliedengdesign/gcode-reference
