### ISSUE TITLE
.gcode Generated by Prusa Slicer Not Recognized

### ISSUE THREAD

**Issue by nverdonk** [appliedengdesign/vscode-gcode-syntax#23]
**Describe the bug**
G-Code files produced by [PrusaSlicer](https://www.prusa3d.com/prusaslicer/) are not recognized or highlighted by extension.  They are .gcode file extensions.

**To Reproduce**

1. Generate G-Code file using PrusaSlicer
2. Save file to Desktop
3. Open file in VS Code
4. Confirm file is not recognized as G-Code

**Expected behavior**
Expect the file type to be recognized and highlighted properly.  VS code seems to recognize that it is a gcode language but extension does not (see screenshot below), 

**Screenshots**
![SNAG-0044](https://user-images.githubusercontent.com/46147269/114598307-99fbec80-9c46-11eb-859e-9e769f4382db.png)

**Environment / Version:**

- OS Version: Windows 10
- VSCode Version: 1.55.2
- Extension Version: v0.5.1

**Additional context**
I might be missing a step in the process here as the extension is working properly if I make a blank .gcode file and type some commands in.
I have also copied all the text from the PrusaSlicer generated file and pasted into the user-made file and correct highlighting occurs

Let me know if this should be moved, tagged, or deleted.

**Comment by mikecentola** [comment]
@nverdonk can you attach the file here so I can try it on my computer with the current dev version?

**Comment by nverdonk** [comment]
@mikecentola Yes, here is a file to play around with.  I just sliced it now and confirmed the same issue is occurring.

Had to ZIP it as GitHub won't allow native upload of .gcode
[Drive Gear.zip](https://github.com/appliedengdesign/vscode-gcode-syntax/files/6311804/Drive.Gear.zip)

**Comment by mikecentola** [comment]
@nverdonk I'm on it!

**Comment by BelKed** [comment]
Visual Studio Code does not colorise that big files...
![Error](https://user-images.githubusercontent.com/66956532/114735063-1ecd3000-9d45-11eb-9b81-61b29ccf74f3.png)
You can enable it by clicking on "Forcefully Enable Features" or in settings – `editor.largeFileOptimizations`

**Comment by mikecentola** [comment]
@nverdonk yup @belkid is correct. I got the same error

![image](https://user-images.githubusercontent.com/12663057/114736380-0abd0a80-9d14-11eb-9e65-edec9cb37667.png)

**Comment by nverdonk** [comment]
### Highlighting Fixed
Toggling `editor.largeFileOptimizations` corrected the highlighting issue, but the G-Code Tree from the extension still claimed to not recognize the G-Code file.

This time, however, a loading bar showed up; perhaps the file is too large for the tree as well?
![gcode_tree](https://user-images.githubusercontent.com/46147269/114736479-f9b3cf80-9cfa-11eb-9609-4243a2d76436.gif)

**Comment by mikecentola** [comment]
@nverdonk Could be because the file is so large. Let me do some investigating on that side as well.

**Comment by nverdonk** [comment]
@mikecentola @BelKed Thank you for such quick responses and help!

@mikecentola I believe the file size is the issue with the tree.  I deleted pretty much the whole file (~550,000 lines to 374 lines) and the tree loads correctly now.
![image](https://user-images.githubusercontent.com/46147269/114738480-dbe76a00-9cfc-11eb-8594-30e5680e7ea1.png)

The tree would be so cumbersome for a file of that size anyway; don't think this will ruin anyone's workflow :), just wanted to make sure it wasn't a bug.

**Comment by mikecentola** [comment]
No worries. I wonder if I should add a detection for large files to not even try if it's over a certain size.

**Comment by nverdonk** [comment]
I think adding note or warning along the lines of

_This file exceeds maximum readable file size of _____ MB.  VS Code might disable highlighting and GCODE tree will not generate_

would help catch people in my situation in the future.

**Comment by mikecentola** [comment]
@nverdonk yeah for sure. I'll see if I can find somewhere to add it. I'm working on the hover code right now.

**Comment by mikecentola** [comment]
I added a warning popup for anything over 10K lines when autoRefresh is enabled.

**Comment by nverdonk** [comment]
I think that's a great addition and will save people a lot of headache in the future!  I'll close out the issue for now and we can reopen if needed.
