### ISSUE TITLE
Highlighting inconsistency with macro variables & control functions

### ISSUE THREAD

**Issue by zachallaun** [appliedengdesign/vscode-gcode-syntax#29]
First off, thanks for all the work that's been put into this! Really happy with it overall.

I ran into a couple highlighting issues while working on a macro. Please see the screenshot below. Things that seem "off" in the screenshot:

* `DO` and `GOTO` are being highlighted inconsistently (this seems to be the case on their own line as well)
* The last closing `]` on the `IF` line does not match the opening bracket in the same way that it does on the `WHILE` line

![image](https://user-images.githubusercontent.com/503938/122300963-0b1d8180-cece-11eb-9c05-ab46fda0f565.png)

**Comment by mikecentola** [comment]
Probably happened when I tweaked the Regex's for the coloring on the last update. I'll try to get it fixed up in the next update!

**Comment by mikecentola** [comment]
Fixed in v0.7.0
