### ISSUE TITLE
Enhancement: Support for square brackets

### ISSUE THREAD

**Issue by proulxwz** [appliedengdesign/vscode-gcode-syntax#3]
Please see in this screenshot how square brackets are used for complex variable assingment and for logic evaluation:

![image](https://user-images.githubusercontent.com/47320932/52207362-85a95180-287d-11e9-8dce-bedb635283eb.png)

It would be useful to have the brackets/content highlighed and also when used in complex variable assignments clearly depicted as variables

**Comment by mikecentola** [comment]
Do you think that the highlighting of a bracket should override any highlighting inside? Highlighting the brackets themselves should be easy.

**Comment by shapesorter** [comment]
I prefer the full set of brackets to be stand out, in programs I tried to make it like this:
![image](https://user-images.githubusercontent.com/7110465/64036964-755f0980-cb22-11e9-93b2-994ff7ae2119.png)

**Comment by mikecentola** [comment]
Fixed in v0.2.0
