### ISSUE TITLE
Wrong "Tool Changes" count

### ISSUE THREAD

**Issue by 7enso** [appliedengdesign/vscode-gcode-syntax#31]
"M6" in comments is counted as tool change. This is problematic in some code cause "M6" also means metric 6 mm thread - for example in the description of a tool.

Leads to "Tool Changes" count being wrong.

**Comment by mikecentola** [comment]
Do you mean using M6 in a comment? I'm unfamiliar with where M6 would be used as an M-Code to indicate thread pitch.

**Comment by 7enso** [comment]
Yes, I mean just using "M6" somewhere in the comments is counted as a tool change so the count gets wrong. Using M6 not as an M-Code but for naming a tool in the comments for example. M6 in the whole world outside the US means "Metric 6 mm thread" and is used often in naming thread milling tools.

https://en.wikipedia.org/wiki/ISO_metric_screw_thread

Maybe you can somehow ignore the patterns used in comments for the tool change count?

**Comment by mikecentola** [comment]
@7enso yeah good call. I'll see if I can have it ignore anything in comments when it's calculating.

**Comment by mikecentola** [comment]
Just fixed this in the dev code, so it'll be in the next release!
