### ISSUE TITLE
Support for coloring .eia files

### ISSUE THREAD

**Issue by shapesorter** [appliedengdesign/vscode-gcode-syntax#4]
Is it possible for me to make .eia files use this scheme, I cant seem to add it to the list in a Json.

**Comment by mikecentola** [comment]
I'll add it to the next hotfix :)

**Comment by shapesorter** [comment]
Thank You, I like your coloring scheme for the most part, I am a bit out of my element offering help, but I will be using it for now.  Thank you for putting it out there for me to use, and getting back to me so fast.

**Comment by mikecentola** [comment]
Absolutely! I'm trying to get back into the swing of things and do more development on this project :)

**Comment by shapesorter** [comment]
So, I realized a few days ago that I can enable coloring to work on the .EIA files as you have it set up now.  I needed to uconfigure it properly.  I can associate any file type.  I should now tell myself to read the documentation.
![image](https://user-images.githubusercontent.com/7110465/65761802-90a34180-e0ed-11e9-8eba-b01a88604224.png)

**Comment by mikecentola** [comment]
Fixed in v0.2.0
