### ISSUE TITLE
auto update not working

### ISSUE THREAD

**Issue by sslupsky** [appliedengdesign/vscode-gcode-syntax#43]
**Describe the bug**
I am not sure if you are aware but the latest version showing in the VSCode is 0.7.0 but I see there have been a few updates since then and the current version is 0.7.4.

**Comment by sslupsky** [comment]
Here is a screenshot.
<img width="925" alt="Screen Shot 2022-08-24 at 3 45 08 PM" src="https://user-images.githubusercontent.com/16888734/186529180-cba9074f-32a5-4c67-8633-cf0bb9b6c0b6.png">

**Comment by mikecentola** [comment]
@sslupsky what version is your VSCode? v0.7.4 requires `^1.69.0`

I'm showing this in mine:

![image](https://user-images.githubusercontent.com/12663057/186931895-2487c799-dc26-4632-befe-660f75a28198.png)

**Comment by sslupsky** [comment]
I have tried it with both 1.69 and 1.70.  Currently on 1.69.2.

**Comment by sslupsky** [comment]
Odd, today it appears to have updated somewhere along the way ... version shows 0.7.4 now.  How long does it typically take for an update to propagate?  Since I installed the plugin into a clean install of VSCode, I expected that 0.7.4 would have installed by default since no previous version of the extension was installed.  Also, I could not find any way to "force an update".

I'll close this issue.

**Comment by mikecentola** [comment]
@sslupsky That is odd for sure and I've never seen that. Keep an eye on it and let me know anything like that happens again.
