### ISSUE TITLE
Missing activity bar icon

### ISSUE THREAD

**Issue by Psychlist1972** [appliedengdesign/vscode-gcode-syntax#5]
Activity bar icon is empty. 4k screen at 100% DPI.

![Annotation 2020-01-10 194026](https://user-images.githubusercontent.com/1421146/72195630-3ea6d300-33e1-11ea-8755-c4ac14f9e38c.jpg)

**Comment by mikecentola** [comment]
That's not right. I'll see whats going on and add it to a hotfix.

**Comment by mikecentola** [comment]
Moved the icon into the resources folder instead. Let's see if that fixes it for you. 0.3.1 incoming.

**Comment by mikecentola** [comment]
Just pushed it out. Let me know if that fixed it.

**Comment by mikecentola** [comment]
@Psychlist1972 did the update fix it for you?

**Comment by mikecentola** [comment]
Closing this.
