### ISSUE TITLE
Question: How to add an extension?

### ISSUE THREAD

**Issue by BernardG** [appliedengdesign/vscode-gcode-syntax#7]
For a French CNC Machines builder, they need a .PRG extension to recognize the G-Code file. What would I need to do to add this extension to those already recognized?

I saw they are listed in package.json, but I guess adding an extension there might not be enough?

Thanks for your help,
Bernard

**Comment by mikecentola** [comment]
I will add it to the 0.3.1 hotfix.

**Comment by mikecentola** [comment]
Added to [v0.3.1](https://github.com/appliedengesign/vscode-gcode-syntax/releases/tag/v0.3.1)

**Comment by BernardG** [comment]
Thanks!
