### ISSUE TITLE
G-Code Tree disappear from available views

### ISSUE THREAD

**Issue by BernardG** [appliedengdesign/vscode-gcode-syntax#8]
It has been working, so I am not sure what I did, but now I am unable to display the tree view, which, to me, is very handy to have. How do I get it back?

![image](https://user-images.githubusercontent.com/2795161/72217565-1c6f9b00-3530-11ea-8dc5-cde70e54a457.png)

**Comment by mikecentola** [comment]
The extension is written to hide the tree view when you’re not viewing a gcode file. Maybe I’ll change it to clear it and disable refresh but not hide it. 

Is it missing even when you’re viewing a gcode file?

**Comment by BernardG** [comment]
Yes, once it has been disappearing, it does not show again when getting back to the G-Code file, and it's not available in the  view list, as shown on the screen shot.

**Comment by mikecentola** [comment]
> Yes, once it has been disappearing, it does not show again when getting back to the G-Code file, and it's not available in the view list, as shown on the screen shot.

Ok let me pull it up tomorrow and take a look at the activation code.
