### ISSUE TITLE
Markup issue with division symbol

### ISSUE THREAD

**Issue by CodeDabbler23** [appliedengdesign/vscode-gcode-syntax#9]
There is an issue with the markup associated with the division symbol caused by block commenting.
Please see the attached photo.
Really love your extension for managing CNC code - nice work!

![DivisionSymbolMarkup](https://user-images.githubusercontent.com/35739725/73326641-e82ef680-4220-11ea-8138-78a75f1d9719.png)

**Comment by mikecentola** [comment]
Working on a hotfix for it right now. Thanks for the kind words!

**Comment by mikecentola** [comment]
Just pushed v0.3.2 and removed that line. @CodeDabbler23 please confirm and I'll close the issue. Thanks!

**Comment by CodeDabbler23** [comment]
Looks good - thanks!!
I have some other thoughts and ideas, what is the best way to communicate those to you?

**Comment by mikecentola** [comment]
Keybase chat, Facebook, Twitter, or email me? Should be able to find me pretty easily ;)
